export const AccountSettingsPage= ()=> {
    // Return objects containing Cypress commands
    return {
        settingsButton: () => cy.get('[data-testid="Settings"]'),
        account: () => cy.get('[data-testid="Account information"]').first(),
        changeEmailAddress: () => cy.get('[data-testid="changeEmail"]'),
        newEmailField: () => cy.get('[data-testid="newEmail"]'),
        currentPasswordField: () => cy.contains('currentPassword'),
        saveEmailButton: () => cy.get('saveEmailButton'),
        xButton: () => cy.contains(' cancel'),
        changePassword: () => cy.get('[data-testid="changePassword"]'),
        oldPasswordField: () => cy.get('[data-testid="oldPassword"]'),
        newPasswordField: () => cy.get('[data-testid="newPassword"]'),
        confirmPasswordField: () => cy.get('[data-testid="confirmPassword"]').first(),
        savePasswordButton: () => cy.get('[data-testid="savePasswordButton"]'),
        genderSelection: () => cy.get('[data-testid=" genderSelection"]'),
        genderSelectionTab: () => cy.contains('SelectionTab'),
        locationCustomization: () => cy.get('selectyourlocation'),
        locationCustomizationTab: () => cy.contains(' selectTab'),
        connectToTwitter: () => cy.get('[data-testid="connectToTwitter"]'),
        connectToGoogle: () => cy.get('[data-testid="connectToGoogle"]'),
        connectToApple: () => cy.get('[data-testid="connectToApple"]'),
        deleteAccountButton: () => cy.get('[data-testid="deleteAccountButton"]'),
        profile: () => cy.get('[data-testid="profile"]'),
        displayName : () => cy.get('[data-testid=" displayName "]'),
        about: () => cy.contains('about'),
        addSocialLinksButton: () => cy.get('addSocialLinksButton'),
        addSocialLinkScreen: () => cy.contains('  addSocialLinkScreen'),
        chooseTypeOfLink: () => cy.get('[data-testid="chooseTypeOfLink"]'),
        displyText: () => cy.get('[data-testid="displyText"]'),
        putLink: () => cy.get('[data-testid="putLink"]'),
        saveTheLink: () => cy.get('[data-testid="saveTheLink"]'),
        uploadAvatarImageButton: () => cy.get('[data-testid="uploadAvatarImageButton"]'),
        uploadBannerImageButton: () => cy.get('uploadBannerImageButton'),
        nsfwSwitch : () => cy.get('nsfwSwitch'),
        allowPeopleToFollowYouSwitch: () => cy.contains(' allowPeopleToFollowYou'),
        contentVisibilitySwitch: () => cy.get('contentVisibility'),
        activeInCommunitiesVisibilitySwitch: () => cy.contains('   activeInCommunitiesVisibility'),
        clearHistoryButton: () => cy.get('[data-testid="clearHistory"]'),
        safetyAndPrivacy: () => cy.get('[data-testid="safety"]'),
        addNewCommunitiesYouWantToMuteButton: () => cy.get(' addNewCommunitiesYouWantToMute'),
        feedSettings: () => cy.contains('  feedSettings'),
        showMatureContentSwitch: () => cy.get('[data-testid="showMatureContent"]'),
        autoplayMediaSwitch: () => cy.get('[data-testid="autoplayMedia"]'),
        contentVisibilitySwitch: () => cy.get('[data-testid="contentVisibility"]'),
        communityThemesSwitch: () => cy.get('[data-testid="communityThemesSwitch"]'),
        communityContentSortCheck: () => cy.get('[data-testid="communityContentSort"]'),
        globalContentViewCheck: () => cy.get('globalContentView'),
        openPostsInNewTabSwitch : () => cy.get('openPostsInNewTab'),
        notification: () => cy.contains(' notification'),
        mentionsofUsernameSwitch: () => cy.get('mentionsofUsername'),
        commentsOnYourPostsSwitch: () => cy.contains('  commentsOnYourPosts'),
        upvotesOnYourPostsSwitch: () => cy.get('upvotesOnYourPosts'),
        repliesToYourCommentsSwitch: () => cy.get('repliesToYourComments'),
        newFollowersSwitch: () => cy.get(' newFollowersSwitch'),
        postsYouFollowSwitch: () => cy.contains(' postsYouFollow'),
        emails: () => cy.get('[data-testid="emails"]'),
        newFollowersEmailSwitch: () => cy.get('[data-testid="newFollowersEmail"]'),
        chatRequestSwitch: () => cy.get('[data-testid="chatRequest"]'),
        unsubscripeFromAllEmailsSwitch: () => cy.get('[data-testid=" unsubscripeFromAllEmails"]'),
       
            
       
    };
}


